#ifndef DATABASE_CONSTS_H
#define DATABASE_CONSTS_H

enum RETURN_CODE {
	NO_ERROR = 0,

	DATABASE_PATH_NOT_FOUND = 100,

	INDEX_NO_DATA = 200,
	INDEX_FILE_DELETED = 201,
};

#endif // DATABASE_CONSTS_H
